### ISSUE TITLE
FtpClient2TLSNativeTest test failed

### ISSUE THREAD

**Issue by amottier** [waarp/Waarp-All#100]
I'm trying to build Wraap from source for and with Java 11. I'm doing that using GitLab CI (see my [gitlab-ci.yml](https://gitlab.ow2.org/ow2/oscar/waarp/-/blob/master/.gitlab-ci.yml)). It basically get the branch `v3.6` and try to build it by running `mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -P jre11 clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report` (with Maven 3.8.1 and OpenJDK 11).

Test failed but the logs does not give much information about the cause of the failure:
```
08:32:37.811 [main] WARN  org.waarp.ftp.client.AbstractFtpClient - org.waarp.ftp.client.AbstractFtpClient.stopServer(AbstractFtpClient.java:96) : Will shutdown from client
08:32:38.084 [Command-5] WARN  org.waarp.ftp.core.command.internal.INTERNALSHUTDOWN - org.waarp.ftp.core.command.internal.INTERNALSHUTDOWN.exec(INTERNALSHUTDOWN.java:82) : Shutdown...
SHUTDOWN: System shutdown
08:32:38.089 [Command-5] WARN  org.waarp.ftp.core.utils.FtpChannelUtils - org.waarp.ftp.core.utils.FtpChannelUtils.exit(FtpChannelUtils.java:343) : Exit: Give a delay of 500 ms
08:32:38.090 [main] WARN  org.waarp.ftp.client.AbstractFtpClient - org.waarp.ftp.client.AbstractFtpClient.stopServer(AbstractFtpClient.java:120) : Will stop server
ERROR Exit System
477833 [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.953 s <<< FAILURE! - in org.waarp.ftp.client.FtpClient2TLSNativeTest
477834 [ERROR] org.waarp.ftp.client.FtpClient2TLSNativeTest.test0_0FtpApacheZ  Time elapsed: 0.373 s  <<< FAILURE!
java.lang.AssertionError: No KO expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
```

You can view the CI job log here: https://gitlab.ow2.org/ow2/oscar/waarp/-/jobs/63217

Maybe this is related to #99 ?

**Comment by fredericBregier** [comment]
Hi,

Issue was sadly identified just after releasing 3.6.0. Thé test test0_0FtpApacheZ is wrong (was more intend To check if Apache supports mode z, but it s not).
The update 3.6.1 removes this buggy test and upgrade dependencies. You can pick it from my own repo if you want or simply deactivate this test.

**Comment by amottier** [comment]
Thanks, I confirm that I can build version 3.6.1 successfully using your fork.

On a side note I realized that `sonar.coverage.jacoco.xmlReportPaths` includes references to files such as `${root.directory}/WaarpAdministrator/target/site/jacoco-aggregate/jacoco.xml` making the build of `WaarpAdministrator` module a requirement and by consequence making usage of `deprecated` profile mandatory in order to run Sonar plugin. I don't see any easy fix for that and always including `deprecated` profile when executing Sonar plugin seems to be an acceptable solution.

**Comment by fredericBregier** [comment]
@amottier Thanks to find out the issue on Jacoco (didn't noticed the warning).
I can change this easily since from 3.6, WaarpAdministrator and other deprecated modules are not compiled by default and were never included within Sonar report whatever (no tests within due to too old codes, even if they are still working more or less).

**Comment by fredericBregier** [comment]
@amottier Thanks !

**Comment by amottier** [comment]
I can confirm that the test now pass and that `deprecated` profile is no longer needed. Thanks @fredericBregier!
