### ISSUE TITLE
Waarp Password does not work

### ISSUE THREAD

**Issue by Tungst3n3** [waarp/Waarp-All#11]
Hi,

On CentOS and Windows, waarp-password.sh / waarp-password.bat does not work correctly.

```
./bin/waarp-password.sh -ki ../waarp-certs/cryptokey.des -pwd adminpwd -po outputpwd.txt
Error: Could not find or load main class org.waarp.uip.WaarpPassword
```

After checking, the classe org.waarp.uip.WaarpPassword is not in share/lib/WaarpR66-3.3.0-jar-with-dependencies.jar
WaarpR66 Version : 3.3 / 3.2

Best Regards
TM

**Comment by fredericBregier** [comment]
Hi @Tungst3n3 
Indeed, we forgot the dependency.
You can use the WaarpPassword-3.3.0.jar in the meantime we fix it.
(available here: https://github.com/waarp/WaarpMaven2/tree/master/maven2/Waarp/WaarpPassword/3.3.0)
Thanks !!
Frédéric

**Comment by Tungst3n3** [comment]
Thanks for your quick response,
I will see that tomorrow.
--------------------------
Merci pour votre retour rapide.
Je regarderai ce point demain, et je cloturerai l'Issue si c'est OK pour pour.

Cordialement / Bests Regards
TM

**Comment by fredericBregier** [comment]
Note: you will need to add WaarpCommon and WaarpDigest in the classpath in addition to WaarpPassword...

**Comment by Tungst3n3** [comment]
Hi,

It works / Ca marche.
Thanks / Merci

TM
