### ISSUE TITLE
Escaping issue in rules whose path contain "\"

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#22]
**Steps to reproduce**

1. Go to the rule page in the admin interface and select a rule to edit.
2. Change a path to contain `\` (for example `C:\Data\`) 
   ![2020-04-30-105750_264x39_scrot](https://user-images.githubusercontent.com/587017/80692800-6b870f00-8ad2-11ea-9106-efff053eb735.png)
3. Update the rule. 
4. In the resulting list, the path contains `\\` instead of `\`
   ![2020-04-30-105806_432x85_scrot](https://user-images.githubusercontent.com/587017/80692969-a38e5200-8ad2-11ea-9192-5ef2700e9f10.png)
5. When re-editing the rule, the `\\` are kept
   ![2020-04-30-105839_277x49_scrot](https://user-images.githubusercontent.com/587017/80693099-d46e8700-8ad2-11ea-963e-6d8e059a944a.png)
6. Saving the rule without fixing the paths will re-double the `\`, and so on
   ![2020-04-30-105853_412x82_scrot](https://user-images.githubusercontent.com/587017/80693210-f700a000-8ad2-11ea-9a4a-efaa6bed48da.png)

**Comment by fredericBregier** [comment]
See #23
