### ISSUE TITLE
[WaarpGatewayFTP] The server exits as soon as it has started

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#24]
The servers starts correctly, but shuts down right after.

I tried with several versions, the issue seems to have appeared somewhere between the switch from the old repo and the 3.1 version.

I attached a full debug log of the execution.
[gwftp.log](https://github.com/waarp/Waarp-All/files/4574308/gwftp.log)

**Comment by fredericBregier** [comment]
See #25
