### ISSUE TITLE
[WaarpR66] Possible reuse of closed database connection in HttpResponsiveSslHandler

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#26]
Here are the logs:

> 04/05/2020/16:23:00.498 ERROR [org.waarp.common.database.DbPreparedStatement] [HttpWorker-27] org.waarp.common.database.DbPreparedStatement.createPrepareStatement(DbPreparedStatement.java:235) : [MYSERVER] SQL Exception createPreparedStatement from jdbc:postgresql://127.0.0.1:5432/waarp_r66:SELECT GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID FROM  RUNNER  WHERE SPECIALID >= ?  AND SPECIALID <= ?  AND IDRULE LIKE '%%'  AND ( REQUESTED LIKE '%%' OR REQUESTER LIKE '%%' ) AND  OWNERREQ = 'MYSERVER'  ORDER BY STARTTRANS DESC  LIMIT 48 This connection has been closed.
> 04/05/2020/16:23:00.498 ERROR [org.waarp.common.database.DbSession] [HttpWorker-27] org.waarp.common.database.DbSession.error(DbSession.java:263) : [MYSERVER] SQLException: This connection has been closed. SQLState: 08003VendorError: 0
> 04/05/2020/16:23:00.498 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-27] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.setDbTaskRunnerJsonData(HttpResponsiveSslHandler.java:208) : [MYSERVER] OpenR66 Web Error SQL Exception createPreparedStatement: SELECT GLOBALSTEP,GLOBALLASTSTEP,STEP,RANK,STEPSTATUS,RETRIEVEMODE,FILENAME,ISMOVED,IDRULE,BLOCKSZ,ORIGINALNAME,FILEINFO,TRANSFERINFO,MODETRANS,STARTTRANS,STOPTRANS,INFOSTATUS,UPDATEDINFO,OWNERREQ,REQUESTER,REQUESTED,SPECIALID FROM  RUNNER  WHERE SPECIALID >= ?  AND SPECIALID <= ?  AND IDRULE LIKE '%%'  AND ( REQUESTED LIKE '%%' OR REQUESTER LIKE '%%' ) AND  OWNERREQ = 'MYSERVER'  ORDER BY STARTTRANS DESC  LIMIT 48

The same error happens with rules, hosts, export, etc., always in HttpResponsiveSslHandler

**Comment by fredericBregier** [comment]
See #27
