### ISSUE TITLE
Usability issues in R66 admin interface

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#35]
In the "Transfers > Listing" and "Transfers > Cancel/restart" pages:
* sorting does not work for the `specialid` column
* The "clear" button does not work if the list has already been filtered (a click on "clear" works just after having typed text though)

**Comment by fredericBregier** [comment]
Sadly, for these issues, it could be difficult to provide a good fix:


1. Responsive format only (no sort on Fixed mode): Sorting does not work, indeed (on this column). I found the reason: the ID is a native "long" but the javascript capability is limited to a shortest long than in Java (16 digits against 19, 2^53 vs 2^63).

- Proposal: If we set as a String ('number'), then it is working correctly (but the ' character appears)

2. "Clear" Button is a "Reset" Type which therefore acts as it should according to definition:

> input elements of type "reset"  are rendered as buttons, with a default click event handler that resets all of the inputs in the form to their initial values.

So the values, once the form posted, are stored in the various fields and "Clear" will restore to those new default values if they are changed, but not "Cleared". 

- Proposal: Therefore what we can do is changing the "text" from "Clear" to "Reset".
- Other proposal: Try to add a "javascript" function that really "clear" all fields (a little bit heavy, but doable)

@bcarlin WDYT?

**Comment by fredericBregier** [comment]
@bcarlin  See #39 for a proposal (All proposals implemented)

**Comment by fredericBregier** [comment]
A side note: transforming number to string implies some bad sort:
- 999 < 1000
- '999' > '1000'

**Comment by bcarlin** [comment]
For the first point, I managed to do it right.
specialid is already a string in the data generated by server:
![2020-05-21-190930_624x36_scrot](https://user-images.githubusercontent.com/587017/82585784-e5249100-9b96-11ea-91c6-74a95080649e.png)

So there is no need to convert it again in `renderSpecialId()` (maybe the reason why you have a `'` char).

It is possible to have a numeric sort of strings in javascript with `String.localCompare()` (available in all browsers and IE 11, so it should be ok to use!). The pitfall is that the negative numbers are handled as positive numbers (the minus sign is ignored). a small fix achieve the right result:

```js
a = ["-3", "-4", "999", "1000", "-999", "-1000"];
a.sort(function(a, b) {
  return ((a[0]=='-'&&b[0]=='-') ? -1: 1) * a.localeCompare(b, undefined, {
    numeric: true,
    sensitivity: 'base'
  });
});
// return value: ["-1000", "-999", "-4", "-3", "999", "1000"]
```
Last step is to implement this sort method in datatable. This can be done by creating a new data type "specialid" with the right sorting methods.

Here is the full diff:

```diff
--- Listing.html	2020-05-21 19:23:32.100287313 +0200
+++ Listing.fixed.html	2020-05-21 19:06:50.126743000 +0200
@@ -70,6 +70,21 @@
   <!-- Tablesorter: special Javascript -->
   <script type="text/javascript">
 var table;
+jQuery.extend( jQuery.fn.dataTableExt.oSort, {
+    "specialid-asc": function ( a, b ) {
+      return ((a[0]=='-'&&b[0]=='-') ? -1: 1) * a.localeCompare(b, undefined, {
+        numeric: true,
+        sensitivity: 'base'
+      });
+    },
+
+    "specialid-desc": function ( a, b ) {
+      return -1 * ((a[0]=='-'&&b[0]=='-') ? -1: 1) * a.localeCompare(b, undefined, {
+        numeric: true,
+        sensitivity: 'base'
+      });
+    }
+} );
 var prepareTable = function() {
 	var activeString = ' <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>';
 	var pushString = '<span class="glyphicon glyphicon-export" aria-hidden="true"></span>';
@@ -92,7 +107,7 @@
 	var renderGeneric = function (data, type, full, meta) {return changeValueColumn(data, meta.col);};
 
 	var myData = XXXDATAJSONXXX;
-	var myColumns = [{ data: "SPECIALID", title : i18n.t("menu2.entete1"), render: renderSpecialId},
+	var myColumns = [{ data: "SPECIALID", title : i18n.t("menu2.entete1"), render: renderSpecialId, type: "specialid"},
 					 { data: "IDRULE", title :i18n.t("menu2.entete2")},
 					 { data: "MODETRANS", title :i18n.t("menu2.entete24"), render: renderGeneric},
 					 { data: "OWNERREQ", title :i18n.t("menu2.entete25"), render: renderOWNERREQ},
```

**Comment by fredericBregier** [comment]
@bcarlin Thanks! I test up also with "long" format number (-9223372036854775805, 9223372036854775805) and it works like a charm.
The PR is updated.
