### ISSUE TITLE
The REST v2 API ignores a user's admin attribute in authorization

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#37]
In the REST v1 API, a user with `admin = true` as a *de facto* `FULLADMIN` role.

However, in the REST v2 API, a user with `admin = true` as a *de facto* `NOACCESS` role.

**Comment by fredericBregier** [comment]
@bcarlin I will need more time for this one, since I did not look into REST V2.

**Comment by bcarlin** [comment]
I don't know what the best way to fix this is.

Authentication is done [here](https://github.com/waarp/Waarp-All/blob/v3.3/WaarpR66/src/main/java/org/waarp/openr66/protocol/http/restv2/resthandlers/RestHandlerHook.java#L286), and authorization [here](https://github.com/waarp/Waarp-All/blob/v3.3/WaarpR66/src/main/java/org/waarp/openr66/protocol/http/restv2/resthandlers/RestHandlerHook.java#L411).

Maybe it can be done [here](https://github.com/waarp/Waarp-All/blob/v3.3/WaarpR66/src/main/java/org/waarp/openr66/protocol/http/restv2/resthandlers/RestHandlerHook.java#L124) by skipping authorization checks altogether if the user is an admin...

**Comment by fredericBregier** [comment]
It turns out that previous fix (Business fix, in particular ROLE) resolves this issue.
However I added new tests for these for REST V2 (and some extra fix on REST V2 on previous bad usage of Transfer initialization not found until now). (one fix for REST V2)

I'm currently testing it.

**Comment by fredericBregier** [comment]
See #40

**Comment by bcarlin** [comment]
It still does not work for me.
I created a user with "is admin" checked

![2020-05-26-181536_1119x112_scrot](https://user-images.githubusercontent.com/587017/82925359-e5010880-9f7d-11ea-8144-196ce8e39d9b.png)
ZQ

but no request on the v2 rest api works:

```
$ http --verify no --auth admin:password GET https://127.0.0.1:8088/v2/transfers
HTTP/1.1 403 Forbidden
content-length: 0
```

**Comment by fredericBregier** [comment]
Additional fixes in PR

**Comment by fredericBregier** [comment]
Fixes finalized
