### ISSUE TITLE
[R66] Listing pages are broken in the admin interface

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#61]
FollowId addition breaks the json included in the html source:

![2020-07-31-114046_487x74_scrot](https://user-images.githubusercontent.com/587017/89022784-d8ed4a80-d322-11ea-84d4-89d67d88eb02.png)

I can only guess it comes from [DbTaskRunner.getJson()](https://github.com/waarp/Waarp-All/blob/v3.4/WaarpR66/src/main/java/org/waarp/openr66/database/data/DbTaskRunner.java#L3791) which uses arrayNode.toString() to generate JSON.

but according to [jackson doc](http://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/node/ArrayNode.html#toString()):

> Method that will produce developer-readable representation of the node; which
> may or may not be as valid JSON. If you want valid JSON output (or output
> formatted using one of other Jackson supported data formats) make sure to use
> ObjectMapper or ObjectWriter to serialize an instance, for example:
> 
>    String json = objectMapper.writeValueAsString(rootNode);

I imagine it also would remove the need to do "manual" cleaning of the json generated.

**Comment by fredericBregier** [comment]
Fix in #68
