### ISSUE TITLE
[R66] self-transfers are not saved in the database unless it fails

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#62]
When I try to do a transfer from an agent to itself, the transfer is not saved in the database.

For example, of these two transfers (from server1 to server1):

![2020-07-31-125251_959x237_scrot](https://user-images.githubusercontent.com/587017/89028953-9f6e0c80-d32d-11ea-915e-fe6e9e368179.png)

Only the second one exists in the database:

![2020-07-31-125317_950x94_scrot](https://user-images.githubusercontent.com/587017/89028965-a7c64780-d32d-11ea-860f-583545e85c01.png)

I only observed this for "transfers to self".

**Comment by fredericBregier** [comment]
Was able to reproduce (rare case: self transfer from direct client, not submit)

**Comment by fredericBregier** [comment]
Fix in #70
