### ISSUE TITLE
[R66] some actions are not shown in the system tab of the https admin interface

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#63]
In the https admin interface, in the system tab, the last row of buttons only shows some actions ("shutdown", "restart", "block" and "export config") when another action has been activated on the page (for example "language"):

![Peek 31-07-2020 15-06](https://user-images.githubusercontent.com/587017/89038309-6723f980-d340-11ea-97e9-ec670bcf935f.gif)

**Comment by fredericBregier** [comment]
Fix in #69
