### ISSUE TITLE
[R66] XMLRuleDAO select, find and exists operations only work on internal cache

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#64]
To avoid lookups on disk every time a Rule is selected, XMLRuleDAO has an internal cache, which is good.

However, `select`, `find` and `exists` operations only works on the internal cache (as opposed to XMLHostDAO which falls bach on disk search if nothing id found in the internal cache).

As the internal cache if only filled when `getAll()` is called, there are some situations where `select`, `find` and `exists` never find rules that do exists.
As a side effect, the file watcher is not working without database: `SpooledDirectoryTransfer` (and its execution tree) never runs `XMLRuleDAO.getAll()` durining its initialization, so the individual lookups for each `spooldirectory`'s rule always fail.

**Comment by fredericBregier** [comment]
Fix in #71
