### ISSUE TITLE
[R66] Commander might be blocked in some cases

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#65]
The commander lists the tansfers to start, and loops on them. 
In the loop, there are two branches with `continue` statements, but the loop index is not incremented before the continue. This results in infinite loops when a transfer enters one of these branches.

https://github.com/waarp/Waarp-All/blob/07caa8a1ee98506d2f3f37f43b1758ef1b12270a/WaarpR66/src/main/java/org/waarp/openr66/commander/Commander.java#L437-L467

Moving the `i++` from line 465 to line 443 should fix this)

**Comment by fredericBregier** [comment]
Fix in #72
