### ISSUE TITLE
The output of client does not escape values according to the target format

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#78]
Some output values can contain XML-like data. 
When we ask the command to format the output in XML with `-xml`, this produce a valid XML structure, but it does not match the intent.

For example, with the output for a failed transfer, I have the following XML (the formatting has been added by me to highlight what I mean):

```xml
<xml>
  <command>DirectTransfer</command>
  <args>etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -xml </args>
  <status>2</status>
  <statusTxt>Transfer in status: FAILED with no Transfer Id</statusTxt>
  <remote>server1</remote>
  <error>
    ErrorPacket:(3:E) PreTask in error: Runner is failed: 
    <STATUS>-1</STATUS>
    <ERROR>will fail </ERROR>
  </error>
</xml>
```

Though it is valid, `<STATUS>` and `<ERROR>` are part of `<error>` and not tags of the main XML document.
The output should use entity refs to protect the content of the `<error>` message:

```xml
<xml>
  <command>DirectTransfer</command>
  <args>etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -xml </args>
  <status>2</status>
  <statusTxt>Transfer in status: FAILED with no Transfer Id</statusTxt>
  <remote>server1</remote>
  <error>
    ErrorPacket:(3:E) PreTask in error: Runner is failed: 
    &lt;STATUS&gt;-1&lt;/STATUS&gt;
    &lt;ERROR&gt;will fail &lt;/ERROR&gt;
  </error>
</xml>
```

*edit:*
I realised by reviewing #67 that the same problem exists for other output formats.

Here is an example with `-csv`. The culprits are the semicolon (`;`) between "will" and "fail" and the new line which are not protected, hence adding an extra column in the first line, and a second record in the second line:

```csv
command;args;status;statusTxt;remote;error
DirectTransfer;etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -csv ;2;Transfer in status: FAILED with no Transfer Id;server1;ErrorPacket:(3:E) PreTask in error: Runner is failed: <STATUS>-1</STATUS><ERROR>will ;fail
always
```

The output should be:

```csv
command;args;status;statusTxt;remote;error
DirectTransfer;etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -csv ;2;Transfer in status: FAILED with no Transfer Id;server1;"ErrorPacket:(3:E) PreTask in error: Runner is failed: <STATUS>-1</STATUS><ERROR>will ;fail
always"
```

**Comment by fredericBregier** [comment]
Proposal will be:
- csv : replace all ';' by ';'
- xml : replace all <, > by [, ] respectively

**Comment by fredericBregier** [comment]
See update of #67
