### ISSUE TITLE
Build failed due to missing waarp theme for Sphinx

### ISSUE THREAD

**Issue by amottier** [waarp/Waarp-All#98]
I'm trying to build (`./mvnw -P jre11 -D skipTests package` using Maven 3.8.1, OpenJDK 11, Debian 10) from branch `v3.6.0` from `fredericBregier` fork (https://github.com/fredericBregier/Waarp-All/tree/v3.6.0) and I get an error related to Sphinx documentation generation:
```
[INFO] --- exec-maven-plugin:3.0.0:exec (SphinxHtml) @ WaarpPackaging ---
Sphinx v4.1.2 en cours d'exécution
chargement des traductions [fr]... fait
création du dossier de destinataire... fait

Theme error:
Le thème nommé 'waarp' n'a pas été trouvé (le fichier theme.conf est-il bien présent ?)
make: *** [Makefile:20: html] Error 2
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
```
Based on [Sphinx configuration file](https://github.com/fredericBregier/Waarp-All/blob/v3.6.0/doc/waarp-r66/source/conf.py#L92) it seems that theme `waarp` is referenced but could not be found.

**Comment by fredericBregier** [comment]
Hi,
The documentation can be build using:

- a clone of git+ssh://git@code.waarp.fr:2222/waarp/sphinx-template.git
  -  Change possibly width 800 to 1400 if you want larger pages
  - Make the installation on top of the cloned directory to your local installation
- Other stuff to install:
  - sphinx
  - sphinx-autobuild
  - sphinxcontrib-openapi
  - sphinx.ext.todo
  - sphinxcontrib-httpdomain
    - Possibly fix the current version 1.6 to 1.7
    - or change sphinxcontrib/httpdomain.py
      - line 766
      - + app.add_domain(HTTPDomain)

**Comment by amottier** [comment]
Thanks, I managed to get sources of `sphinx-template` from https://code.waarp.fr/waarp/sphinx-template.git (I don't have permissions to access to `git+ssh://git@code.waarp.fr:2222/waarp/sphinx-template.git `).

I'm not sure to fully understand "Make the installation on top of the cloned directory to your local installation". Can you provide more guidance?

Also, do you think it would make sense to "build" the `WaarpPackaging` and `WaarpPackaging6` only if a specific Maven profile is enabled? If you think that can be useful I can create a pull request.

**Comment by fredericBregier** [comment]
I think it can be done, but I feel like, as it built the final "all packages" (RPM, DEB, JAR, doc), one shall just ignore it using:

      mvn -P jreX -pl '!WaarpR66Gui,!WaarpAdministrator,!WaarpXmlEditor,!WaarpPackaging,!WaarpPackaging6' something (clean install)

But it might be a good idea to set those packages only available in a specific concurrent profile as you said, such as:

    mvn -P jreX,packaging


Such as, by default, nothing is created (no DEB, RPM, JAR, DOC, except standard jars and all inclusive in previous modules).

WDYT ?

**Comment by fredericBregier** [comment]
Sorry, I come back on the installation of waarp template (I'm not the author of this one): I had to install the package in my Linux.

To do that (currently in vacation, so not my Linux with me), I clone the repository, then i go within the root of this clone (`sphinx-template` directory), and I read some files to understand how to make this module available from my Python/Sphinx installation.

**Comment by amottier** [comment]
I managed to get a successful build ignoring test and ignoring `WaarpPackaging` module with `jre11` profile. But I think performing packaging in a separated profile can be useful so I create a pull request that moves `WaarpPackaging` and `WaarpPackaging6` to dedicated profiles (one per JRE).

**Comment by fredericBregier** [comment]
Thanks @amottier I will integrate your various proposals !!!

**Comment by amottier** [comment]
After installing a bunch of Sphinx packages (I probably installed more then needed) either using Debian packages or using `pip`, installing `latexmk`, building and installing Waarp Sphinx with `pip install .`, installing `rpm` and disabling signing of Debian package I'm managed to do a full build.

So I think this issue is fixed.

**Comment by fredericBregier** [comment]
OK, thank you!!
